[package]
name = "apple_navidrome"
version = "0.1.0"
edition = "2021"

[lib]
name = "apple_navidrome_lib"
path = "src/lib.rs"

[[bin]]
name = "apple_navidrome_cli"
path = "src/cli.rs"

[dependencies]
chrono = "0.4.39"
urlencoding = "2.1.3"
xml = "0.8.20"
